; NodeMCU v2/v3 (ESP-12E)
;[env:esp8266]
;platform = espressif8266@^4.2.1
;board = nodemcuv2
;framework = arduino
;monitor_speed = 115200
;lib_deps =
;    knolleary/PubSubClient@^2.8
;    adafruit/Adafruit SSD1306@^2.5.10
;    adafruit/Adafruit GFX Library@^1.11.9
;    adafruit/RTClib@^2.1.4

; Für Updates per WLAN (OTA) einkommentieren:
; upload_protocol = espota
; upload_port = 192.168.178.x
; upload_flags = --auth=xxxxx

; PlatformIO Project Configuration File

[env:esp12e-ota]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200

; Enable OTA via build flag
build_flags =
    -D OTA_ENABLED

; Upload over WiFi
upload_protocol = espota
upload_port = 192.168.178.x
upload_flags =
    --auth=xxxxx
    --host_port=45678

lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit SSD1306@^2.4.7
    adafruit/Adafruit GFX Library@^1.11.5
    milesburton/DallasTemperature@^3.9.0
    paulstoffregen/OneWire@^2.3.5
    ESP8266WiFi
    RTClib

; -------------------------------------------------------------------

;[env:esp12e-usb]
;platform = espressif8266
;board = esp12e
;framework = arduino
;monitor_speed = 115200

;lib_deps =
;    knolleary/PubSubClient@^2.8
;    adafruit/Adafruit SSD1306@^2.4.7
;    adafruit/Adafruit GFX Library@^1.11.5
;    milesburton/DallasTemperature@^3.9.0
;    paulstoffregen/OneWire@^2.3.5
;    ESP8266WiFi
;    RTClib
